---
title: "Simple document"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
```

## import data, FAS_litters.csv

```{r}

litters_data = read_csv(file = "data_import_examples/FAS_litters.csv")

litters_data

```

## cleaning variable names imported

```{r}
names(litters_data)
## [1] "Group"             "Litter Number"     "GD0 weight"       
## [4] "GD18 weight"       "GD of Birth"       "Pups born alive"  
## [7] "Pups dead @ birth" "Pups survive"


# cleans variables and turns  them into lower snake case
# useful for tidying  variable names of imported csv
litters_data = janitor::clean_names(litters_data) 

names(litters_data)
```


```{r}

pups_data = read_csv(file = "data_import_examples/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data) 
pups_data

```

## select function

```{r}

# select(litters_data, group, litter_number)
# 
# select(litters_data, group, gd0_weight, gd18_weight)
# 
# select(litters_data, group, gd0_weight:gd_of_birth)
# select(litters_data, group, starts_with("pups")) # starts_with, ends_with, contains
# 
# select(litters_data, -litter_number)

select(litters_data, GROUP= group, litter_number)

rename(litters_data, GGROUP = group)

select(litters_data, litter_number, everything())

relocate(litters_data, litter_number)

```

```{r}

select(pups_data, litter_number, sex, pd_ears)
```

```{r}
pull(litters_data, group)
```


## filter

```{r}

filter(litters_data, group == 'Con7')

filter(litters_data,gd0_weight < 21)


filter(litters_data,pups_survive != 4)

filter(litters_data,!(group == 'Con7'))

filter(litters_data, group %in% c("Con7","Con8"))

filter(litters_data, group == 'Con7', gd_of_birth == 20) # and

filter(litters_data, group == 'Con7' | gd_of_birth == 20) # or

drop_na(litters_data,gd0_weight)

```

## mutate

```{r}


mutate(litters_data, weight_change = gd18_weight - gd0_weight) #  define new var off other columns

mutate(
  litters_data,
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)


```


## arrange

```{r}

arrange(litters_data, desc(gd0_weight))

arrange(litters_data, gd_of_birth, gd0_weight)

```

## pipes

```{r}

litters_data_raw = read_csv("data_import_examples/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")

```

```{r}

litters_df = 
  read_csv("data_import_examples/FAS_litters.csv")  %>%
  janitor::clean_names() %>%
  select(group, pups_survive) %>%
  filter(group == "Con7")

```

```{r}

# not as clean:

# litters_df2 = 
#   filter(
#     select(
#       janitor::clean_names(
#         read_csv("data_import_examples/FAS_litters.csv")), 
#       group, pups_survive), 
#     group == "Con7")

```



