---
title: "Simple document"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
```

## import data, FAS_litters.csv

```{r}

litters_data = read_csv(file = "data_import_examples/FAS_litters.csv")

litters_data

```

## cleaning variable names imported

```{r}
names(litters_data)
## [1] "Group"             "Litter Number"     "GD0 weight"       
## [4] "GD18 weight"       "GD of Birth"       "Pups born alive"  
## [7] "Pups dead @ birth" "Pups survive"


# cleans variables and turns  them into lower snake case
# useful for tidying  variable names of imported csv
litters_data = janitor::clean_names(litters_data) 

names(litters_data)
```

## viewing data

```{r}
# litters_data
# tail(litters_data, 5) # last 5
# head(litters_data, 5) # fisrt 5
# view(litters_data) # opens separate tab with data table, make sure commented when knitting
# str(litters_data) # puts all columns into lists
skimr::skim(litters_data) # creates data summary and shows simple hist for each var

```

## arguments in 'read_csv'

```{r}

litters_df = read_csv("data_import_examples/FAS_litters.csv",
                      skip = 5,
                      col_names = FALSE,
                      na = "Low8") #  replace missing data w na

litters_df
```

## Parsing columns

```{r}

litters_data = read_csv(file = "data_import_examples//FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ) # specify column types
)

# short hand for specifying col types
# litters_data = read_csv(file = "./data/FAS_litters.csv",
#   col_types = "ccddiiii"
# )

tail(litters_data)


```

## other file formats

## read_csv (tibbles) better than read.csv

```{r}

library(readxl)

mlb11_data = read_excel("data_import_examples/mlb11.xlsx", n_max = 20)
head(mlb11_data, 20)

```
## only load in certain part of Excel file
```{r}

fellow_df = read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
fellow_df
```



```{r, eval = FALSE}

library(haven)

pulse_data = read_sas("data_import_examples/public_pulse_data.sas7bdat")
head(pulse_data, 5)

```






