---
title: "Tidying data"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer

```{r}

pulse_df = 
  haven::read_sas("data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_df

```
```{r}
pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to="visit",
    names_prefix = "bdi_score_",
    values_to="bdi"
  ) %>%
  relocate(visit) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  ) %>%
  arrange(id, visit)

pulse_tidy

```

# pivot wider

```{r}

analysis_df = tibble(
  group = c("treatment", "treatment", "control", "control"),
  time = c("a", "b", "a", "b"),
  group_mean = c(4, 8, 3, 6)
)

analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>%
  knitr::kable()


```



## bind rows

```{r}

fellowship_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range="B3:D6") %>%
  mutate(movie="fellowship_rings")  # name from corresponding table in Excel

towers_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range="F3:H6") %>%
  mutate(movie="two_towers")  # name from corresponding table in Excel

return_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range="J3:L6") %>%
  mutate(movie="return_king")  # name from corresponding table in Excel

fellowship_df
towers_df
return_df

lotr_df =
  bind_rows(fellowship_df, towers_df, return_df) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>%
  relocate(movie)


lotr_df

```


## join 

```{r}

pup_data = 
  read_csv("data_import_examples/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"),
    sex = factor(sex)) 

litter_data = 
  read_csv("data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>% # dose and treatment column now
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

pup_data
litter_data

```

```{r}

fas_data = 
  left_join(pup_data, litter_data, by="litter_number") %>%
  relocate(litter_number, dose, day_of_tx)
# left_join to include all rows in pup_data

fas_data

```




